In [4]:
import numpy as np

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [6]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [0],
    [0],
    [1]
])

print("Input:")
print(X)

print("\nOutput:")
print(y)

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Output:
[[0]
 [0]
 [0]
 [1]]


In [7]:
np.random.seed(42)

weights = np.random.rand(2, 1)
bias = np.random.rand(1)

print("Initial Weights:")
print(weights)

print("\nInitial Bias:")
print(bias)

Initial Weights:
[[0.37454012]
 [0.95071431]]

Initial Bias:
[0.73199394]


In [8]:
learning_rate = 0.1
epochs = 10000

In [9]:
for epoch in range(epochs):

    # Forward Propagation
    input_layer = X
    weighted_sum = np.dot(input_layer, weights) + bias
    output = sigmoid(weighted_sum)

    # Error Calculation
    error = y - output

    # Backpropagation
    d_output = error * sigmoid_derivative(output)

    # Update Weights and Bias
    weights += learning_rate * np.dot(input_layer.T, d_output)
    bias += learning_rate * np.sum(d_output)

In [10]:
print("Trained Weights:")
print(weights)

print("\nTrained Bias:")
print(bias)

Trained Weights:
[[5.47798131]
 [5.47798133]]

Trained Bias:
[-8.30967052]


In [11]:
print("Predicted Output after Training:")
print(output)

Predicted Output after Training:
[[2.46107665e-04]
 [5.56386310e-02]
 [5.56386303e-02]
 [9.33778435e-01]]
