In [1]:
import numpy as np

In [2]:
# Sigmoid Activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


# Tanh Activation
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.square(x)


# ReLU Activation
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

In [3]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

print("Input:")
print(X)

print("\nTarget Output:")
print(y)

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Target Output:
[[0]
 [1]
 [1]
 [0]]


In [4]:
activation_name = "sigmoid"   # change to "tanh" or "relu"

if activation_name == "sigmoid":
    activation = sigmoid
    activation_derivative = sigmoid_derivative
elif activation_name == "tanh":
    activation = tanh
    activation_derivative = tanh_derivative
elif activation_name == "relu":
    activation = relu
    activation_derivative = relu_derivative

print("Using Activation Function:", activation_name)

Using Activation Function: sigmoid


In [5]:
np.random.seed(42)

input_neurons = 2
hidden_neurons = 2
output_neurons = 1

# Weights and Biases
W1 = np.random.randn(input_neurons, hidden_neurons)
b1 = np.zeros((1, hidden_neurons))

W2 = np.random.randn(hidden_neurons, output_neurons)
b2 = np.zeros((1, output_neurons))

print("Initial W1:\n", W1)
print("\nInitial b1:\n", b1)
print("\nInitial W2:\n", W2)
print("\nInitial b2:\n", b2)

Initial W1:
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]]

Initial b1:
 [[0. 0.]]

Initial W2:
 [[-0.23415337]
 [-0.23413696]]

Initial b2:
 [[0.]]


In [6]:
learning_rate = 0.1
epochs = 10000
losses = []

In [7]:
for epoch in range(epochs):

    # Forward Propagation

    hidden_input = np.dot(X, W1) + b1
    hidden_output = activation(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)   # output layer uses sigmoid


    # Loss Calculation

    loss = np.mean((y - predicted_output) ** 2)
    losses.append(loss)


    # Backpropagation

    error = y - predicted_output

    d_output = error * sigmoid_derivative(predicted_output)

    hidden_error = np.dot(d_output, W2.T)
    d_hidden = hidden_error * activation_derivative(hidden_output)

    # Gradient Descent Update

    W2 += learning_rate * np.dot(hidden_output.T, d_output)
    b2 += learning_rate * np.sum(d_output, axis=0, keepdims=True)

    W1 += learning_rate * np.dot(X.T, d_hidden)
    b1 += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)


    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

Epoch 0, Loss: 0.255830
Epoch 1000, Loss: 0.249406
Epoch 2000, Loss: 0.245445
Epoch 3000, Loss: 0.204707
Epoch 4000, Loss: 0.153204
Epoch 5000, Loss: 0.138691
Epoch 6000, Loss: 0.133594
Epoch 7000, Loss: 0.131151
Epoch 8000, Loss: 0.129749
Epoch 9000, Loss: 0.128849


In [8]:
print("Final Predicted Output:\n")
print(predicted_output)

Final Predicted Output:

[[0.05300868]
 [0.49554213]
 [0.95091319]
 [0.50319888]]


In [9]:
print("Final W1:\n", W1)
print("\nFinal b1:\n", b1)
print("\nFinal W2:\n", W2)
print("\nFinal b2:\n", b2)

Final W1:
 [[ 3.31767851 -3.42562699]
 [ 6.34923419  6.53826925]]

Final b1:
 [[-0.67114569  2.63115182]]

Final W2:
 [[ 4.83785861]
 [-4.77073655]]

Final b2:
 [[-0.06895853]]
